version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore-with-me-stats

  stats-db:
    image: postgres:14-alpine
    container_name: statspostgredb
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6433:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr

  ewm-service:
    build: ewm-service
    image: main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore-with-me-ewm
      - STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewmpostgredb
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=explore-with-me-ewm
      - POSTGRES_USER=kitty
      - POSTGRES_PASSWORD=purrrrrr